/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface ErrorResponseDto {
  statusCode: number;
  message: string;
  error?: string;
}
