/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface TaskResponseDto {
  id: number;
  title: string;
  parentId: number;
  subtasks: TaskResponseDto[];
}
